config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :application_accounts
  end
end

app/models/application_account.rb
class ApplicationAccount < ActiveRecord::Base
  validates :name, :presence => true
end

app/models/application_session.rb
class ApplicationSession < Authlogic::Session::Base
  authenticate_with ApplicationAccount

  params_key :app_key
  login_field false

  single_access_allowed_request_types :any
end

app/controllers/admin/application_accounts_controller.rb
class Admin::ApplicationAccountsController < Admin::ApplicationController
  before_filter :require_user
  before_filter "set_current_tab('admin/application_accounts')", :only => [ :index ]

  # GET /admin/application_accounts
  #----------------------------------------------------------------------------
  def index
    @application_accounts = ApplicationAccount.order(:created_at)
    respond_to do |format|
      format.html # index.html.haml
    end
  end

  # POST /admin/application_accounts
  #----------------------------------------------------------------------------
  def create
    @application_account = ApplicationAccount.new(params["application_account"])
    respond_to do |format|
      if @application_account.save
        flash[:notice] = 'New application account created'
      else
        flash[:notice] = 'There was error creating the application account.'
      end
      format.html { redirect_to :action => :index } # go back to index.haml
    end
  end

  # PUT /admin/application_accounts/1
  #----------------------------------------------------------------------------
  def update
    @application_account = ApplicationAccount.find(params["id"])
    @application_account.attributes = params["application_account"]
    respond_to do |format|
      if @application_account.save
        flash[:notice] = 'New application account created'
      else
        flash[:notice] = 'Please fill out the name and token'
      end
      format.html { redirect_to :action => :index } # go back to index.haml
    end
  end

  # DELETE /admin/application_accounts/1
  #----------------------------------------------------------------------------
  def destroy
    @application_account = ApplicationAccount.find(params["id"])
    respond_to do |format|
      if @application_account.destroy
        flash[:notice] = 'Application account deleted'
      else
        flash[:notice] = 'There was error deleting the application account.'
      end
      format.html { redirect_to :action => :index } # go back to index.haml
    end
  end
end

app/views/admin/application_accounts/index.html.haml
.title
  = t(:application_account_settings, :default => "Application Account Settings")

.list
  .remote
    .section
      - @application_accounts.each do |account|
        = form_tag admin_application_account_path(account), :method => :put do
          .label.top.req Application name:
          = text_field_tag 'application_account[name]', account.name, :style => "width:100px"
          .label.top.req Token:
          = text_field_tag 'application_account[single_access_token]', account.single_access_token, :style => "width:150px"
          = submit_tag 'Update', :name => :update, :style => "width:60px"
        = button_to 'Delete', admin_application_account_path(account.id), :method => "delete", :style => "width:60px"
        .spacer

    .section
      %div
        = t('.create_new_application_key', :default => "Create a new application key")
        = form_tag admin_application_accounts_path, :method => :post do
          .label.top.req Application name:
          = text_field_tag 'application_account[name]', '', :style => "width:100px"
          .label.top.req Token:
          = text_field_tag 'application_account[single_access_token]', '', :style => "width:150px"
          = submit_tag t('.create', :default => 'Create'), :name => :create